package org.example.coroutines

import kotlinx.coroutines.*

fun main() = runBlocking {
    launch {
        delay(1000 )
        println("World")
    }

//    delay(10)
    print("Hello, ")

//    delay(1000)
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End")
    println("End Me")
}
